apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-prometheus
  namespace: rabbitmq
  labels:
    release: prometheus-stack
spec:
  endpoints:
  - port: prometheus
    path: /metrics
    interval: 15s
  - port: prometheus
    path: /metrics/detailed
    interval: 15s
    params:
      family:
      - queue_coordination
      - queue_metrics
  selector:
    matchLabels:
      app.kubernetes.io/part-of: rabbitmq
