apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: vhost-orders
  namespace: orders-system
spec:
  name: vhost_orders
  rabbitmqClusterReference:
    name: rabbitmq-prod
    namespace: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: orders-svc-user
  namespace: orders-system
spec:
  rabbitmqClusterReference:
    name: rabbitmq-prod
    namespace: rabbitmq
  importCredentialsSecret:
    name: orders-svc-credentials
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: orders-svc-permission
  namespace: orders-system
spec:
  rabbitmqClusterReference:
    name: rabbitmq-prod
    namespace: rabbitmq
  user: orders-svc-user
  vhost: vhost_orders
  permissions:
    configure: ".*"
    write: ".*"
    read: ".*"
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: order-events
  namespace: orders-system
spec:
  name: order_events
  vhost: vhost_orders
  type: topic
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq-prod
    namespace: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: order-validation-q
  namespace: orders-system
spec:
  name: order_validation_q
  vhost: vhost_orders
  type: quorum
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq-prod
    namespace: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: order-validation-dlq
  namespace: orders-system
spec:
  name: order_validation_dlq
  vhost: vhost_orders
  type: quorum
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq-prod
    namespace: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: orders-dlx-policy
  namespace: orders-system
spec:
  name: orders_dlx_policy
  vhost: vhost_orders
  pattern: "^order_validation_q$"
  applyTo: queues
  definition:
    dead-letter-exchange: "order_events"
    dead-letter-routing-key: "order_validation_dlq"
  rabbitmqClusterReference:
    name: rabbitmq-prod
    namespace: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-validation-binding
  namespace: orders-system
spec:
  vhost: vhost_orders
  source: order_events
  destination: order_validation_q
  destinationType: queue
  routingKey: "order.#"
  rabbitmqClusterReference:
    name: rabbitmq-prod
    namespace: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: order-validation-dlq-binding
  namespace: orders-system
spec:
  vhost: vhost_orders
  source: order_events
  destination: order_validation_dlq
  destinationType: queue
  routingKey: "order_validation_dlq"
  rabbitmqClusterReference:
    name: rabbitmq-prod
    namespace: rabbitmq
