apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: rabbitmq-policy
  namespace: rabbitmq
spec:
  name: rabbitmq-policy
  pattern: ".*"
  applyTo: queues
  definition:
    message-ttl: 900000
    max-length-bytes: 10737418240
  rabbitmqClusterReference:
    name: rabbitmq-prod
