apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-prod
  namespace: rabbitmq
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "orders-system,payments-system,notifications-system"
spec:
  replicas: 3
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
  persistence:
    storageClassName: "local-path"
    storage: "10Gi"
  rabbitmq:
    additionalConfig: |
      # Enforce all queues to default to Quorum Queues
      default_queue_type = quorum
      prometheus.return_per_object_metrics = true
      ssl_cert_login_from = common_name
      auth_mechanisms.1 = EXTERNAL
      auth_mechanisms.2 = PLAIN
      auth_mechanisms.3 = AMQPPLAIN
    additionalPlugins:
      - rabbitmq_shovel
      - rabbitmq_shovel_management
      - rabbitmq_auth_mechanism_ssl
  tls:
    secretName: rabbitmq-prod-server-cert
    caSecretName: rabbitmq-prod-server-cert

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rabbitmq-prod-pdb
  namespace: rabbitmq
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-prod
