apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-prod-server-cert
  namespace: rabbitmq
spec:
  secretName: rabbitmq-prod-server-cert
  commonName: rabbitmq-prod.rabbitmq.svc.cluster.local
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - budd.codes
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - rabbitmq-prod.rabbitmq.svc.cluster.local
    - rabbitmq-prod-nodes.rabbitmq.svc.cluster.local
    - rabbitmq-prod-server-0.rabbitmq-prod-nodes.rabbitmq.svc.cluster.local
    - rabbitmq-prod-server-1.rabbitmq-prod-nodes.rabbitmq.svc.cluster.local
    - rabbitmq-prod-server-2.rabbitmq-prod-nodes.rabbitmq.svc.cluster.local
  issuerRef:
    name: vault-issuer
    kind: Issuer
    group: cert-manager.io
