apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
  namespace: rabbitmq
spec:
  address: https://vault.budd.codes
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth-prod
  namespace: rabbitmq
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes/prod
  kubernetes:
    role: cert-manager-role
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: shovel-secrets-vault
  namespace: rabbitmq
spec:
  vaultAuthRef: vault-auth-prod
  mount: secret
  path: rabbitmq/shovel
  type: kv-v2
  destination:
    name: shovel-secrets
    create: true
