apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: rabbitmq
spec:
  vault:
    server: https://vault.budd.codes
    path: pki/sign/rabbitmq-role
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes/prod
        role: cert-manager-role
        serviceAccountRef:
          name: default
