apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: rabbitmq-policy
  namespace: rabbitmq
spec:
  name: rabbitmq-policy
  pattern: "^orders-queue$"
  applyTo: queues
  definition:
    dead-letter-exchange: "orders-dlx"
    dead-letter-routing-key: "orders-dlq"
  rabbitmqClusterReference:
    name: rabbitmq-prod
