apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: orders-binding
  namespace: rabbitmq
spec:
  source: orders-exchange
  destination: orders-queue
  destinationType: queue
  routingKey: "orders.#"
  rabbitmqClusterReference:
    name: rabbitmq-prod
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: orders-dlq-binding
  namespace: rabbitmq
spec:
  source: orders-dlx
  destination: orders-dlq
  destinationType: queue
  routingKey: "orders-dlq"
  rabbitmqClusterReference:
    name: rabbitmq-prod

