apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-topology-orders
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/budd9442/orders-rabbitmq-topology.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: orders-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
