apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-topology-notifications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/budd9442/rmq.git'
    targetRevision: HEAD
    path: kubernetes/notifications-rabbitmq-topology
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: notifications-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
